### ISSUE TITLE
LampaKlassrum har ogiltiga ljuskällor

### ISSUE THREAD

**Issue by salmonslay** [LiterallyInc/SajberRoyale#1]
Models/Lampor/LampaKlassrum

- Har 3 ljuskällor utanför föremålet (Light.001, Light.002, Light.003) 
- Ljuskällor för starka (inställda på 1000, bör vara 1)
- Har en kamera tillagd
- Förmodligen för stor?
 ![bild](https://i.imgur.com/bbnaQIx.png)
- Är inte centrerad (0, 0, 0)

**Comment by LiterallyOscar** [comment]
Fiiiiiiiixed!!! uwu <3
